#
# Copyright (c) 2024 NMDP.
#
# This file is part of the NMDP DP Tool 
# (see https://github.com/nmdp-bioinformatics/dpb1-expression).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
FROM python:3.8-alpine

LABEL maintainer="nmdp-bioinformatics"

COPY . /app
RUN mkdir -p /app/logs/
WORKDIR /app

RUN apk add --no-cache --update \
    python3 python3-dev gcc \
    gfortran musl-dev g++ \
    libffi-dev openssl-dev \
    libxml2 libxml2-dev \
    libxslt libxslt-dev \
    libjpeg-turbo-dev zlib-dev

RUN pip install --upgrade cython

# Upgrade pip
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD [ "gunicorn", "--bind", "0.0.0.0:5010", "--log-config", "conf/logging.conf", "wsgi:app" ]